/*******************************************************************************
* _Types_Core generated by MVN.RLLib using UE Explorer.
* MVN.RLLib ? 2019 Martin VN. All rights reserved.
* All rights belong to their respective owners.
*******************************************************************************/
class _Types_Core extends Object
    abstract;

struct native ProductInstanceID
{
    var Qword UpperBits;
    var Qword LowerBits;
};